# backend/app/models/report_history.py
#
# ReportHistory table - stores generated report audit records.
# Tracks report type, filters, generated user, record count, status, and file name.
# Used by the Reports module for report history and audit logging.

import uuid
from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.db.database import Base


class ReportHistory(Base):
    __tablename__ = "report_history"

    # --- Primary Key ---
    report_history_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    # --- Report Details ---
    report_type = Column(String(50), nullable=False, index=True)
    report_title = Column(String(255), nullable=False)

    # --- Generated By ---
    generated_by_user_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    generated_by_name = Column(String(255), nullable=False)

    # --- Report Filters and Result ---
    filters_json = Column(JSONB, nullable=False, default=dict)
    record_count = Column(Integer, nullable=False, default=0)

    # success / failed
    status = Column(String(20), nullable=False, index=True)

    # --- File and Error Details ---
    file_name = Column(String(255), nullable=True)
    error_message = Column(Text, nullable=True)

    # --- Audit Trail ---
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    def __repr__(self):
        return (
            f"<ReportHistory {self.report_type} "
            f"{self.status} {self.created_at}>"
        )