# automated D5 (professional tone) rater using Mistral (mistral-small-2506).
# this is our third rater in the LLM eval study alongside the human rater
# (Allan) and the Claude Chrome extension rater.
#
# flow: log in as the Mistral evaluator account (USR00003) -> fetch all 180
# blind letters from GET /evaluation/letters -> send each letter's text to
# Mistral with a fixed D5 prompt -> turn the Yes/No reply into 1/0 -> POST
# it to /evaluation/score, same endpoint the UI uses so it's stored the
# same way as a human score.
#
# the Mistral account needs to already exist in the DB with is_researcher
# = true before this will work:
#   INSERT INTO users (user_id, user_code, first_name, last_name, email,
#     hashed_password, role, is_active, is_researcher, ...)
#   VALUES (gen_random_uuid(), 'USR00003', 'Mistral', 'Small2506',
#     'allanerasmo@yahoo.com', '<hashed_password>', 'doctor', true, true, ...)
#
# mistral-small-2506 free tier caps out at 2.25M tokens/min and 5 req/sec -
# we pause 0.25s between calls (4 RPS, 80% of the limit) which gets all 180
# letters done in about a minute.
#
# run with:
#   docker exec -it glaucoma_backend python -m scripts.mistral_d5_rater
#
# safe to re-run - already-scored letters get skipped via the is_scored
# flag from GET /evaluation/letters.

import os
import sys
import time
import asyncio
import traceback
import httpx
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.logger import get_logger
from app.core.config import settings

logger = get_logger(__name__)

# config

# backend API, running locally inside the docker network
API_BASE_URL = "http://localhost:8000"

# Mistral evaluator account creds
MISTRAL_EVALUATOR_EMAIL = "allanerasmo@yahoo.com"
MISTRAL_EVALUATOR_PASSWORD = "Admin@1234"  # same as system admin default

# Mistral API config
MISTRAL_MODEL = "mistral-small-2506"
MISTRAL_API_URL = "https://api.mistral.ai/v1/chat/completions"

# 0.25s pause = 4 RPS, comfortably under the 5 RPS limit
PAUSE_BETWEEN_CALLS_SECONDS = 0.25

# same prompt the Claude Chrome extension rater uses, so both AI raters
# are judging against the same criterion
D5_PROMPT = (
    "Your role is a glaucoma specialist; you will read the referral letters "
    "generated by an LLM from the Glaucoma AI Screening System. You will judge "
    "the letter with this guiding question. Does this letter read like a "
    "professional clinical referral a specialist would take seriously? "
    "And just answer Yes or No, without any explanation or any extra word, "
    "just Yes or No."
)


def parse_mistral_response(response_text: str) -> int | None:
    # turns Mistral's Yes/No reply into 1/0, or None if it's ambiguous
    text = response_text.strip().lower()
    if text in ("yes", "yes.", "yes,"):
        return 1
    if text in ("no", "no.", "no,"):
        return 0
    # fall back to checking the start, in case it rambled a bit
    if text.startswith("yes"):
        return 1
    if text.startswith("no"):
        return 0
    return None


async def get_auth_token(client: httpx.AsyncClient) -> str:
    # log in as the Mistral evaluator account, return the JWT
    response = await client.post(
        f"{API_BASE_URL}/auth/login",
        data={
            "username": MISTRAL_EVALUATOR_EMAIL,
            "password": MISTRAL_EVALUATOR_PASSWORD,
        },
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    response.raise_for_status()
    token = response.json().get("access_token")
    if not token:
        raise RuntimeError("Login failed - no access_token in response.")
    logger.info(f"[mistral_rater] Authenticated as {MISTRAL_EVALUATOR_EMAIL}")
    return token


async def fetch_letters(client: httpx.AsyncClient, token: str) -> list:
    # pulls all 180 blind letters from the evaluation API
    response = await client.get(
        f"{API_BASE_URL}/evaluation/letters",
        headers={"Authorization": f"Bearer {token}"},
        timeout=30.0,
    )
    response.raise_for_status()
    data = response.json()
    letters = data.get("letters", [])
    total = data.get("total", 0)
    scored = data.get("scored_count", 0)
    logger.info(f"[mistral_rater] Fetched {len(letters)} letters | total={total} already_scored={scored}")
    return letters


async def score_with_mistral(letter_text: str) -> int | None:
    # sends one letter to Mistral, returns the parsed D5 score.
    # new httpx client each call to dodge connection pooling weirdness over a long run
    mistral_api_key = getattr(settings, "MISTRAL_API_KEY", None)
    if not mistral_api_key:
        raise RuntimeError(
            "MISTRAL_API_KEY not found in settings/environment. "
            "Add it to your .env file as MISTRAL_API_KEY=your_key_here"
        )

    payload = {
        "model": MISTRAL_MODEL,
        "messages": [
            {"role": "system", "content": D5_PROMPT},
            {"role": "user", "content": letter_text},
        ],
        "max_tokens": 5,       # just Yes/No, no room for rambling
        "temperature": 0.0,    # deterministic - same letter, same score every time
    }

    async with httpx.AsyncClient(timeout=30.0) as mistral_client:
        response = await mistral_client.post(
            MISTRAL_API_URL,
            json=payload,
            headers={
                "Authorization": f"Bearer {mistral_api_key}",
                "Content-Type": "application/json",
            },
        )
        response.raise_for_status()

    data = response.json()
    raw_text = data["choices"][0]["message"]["content"]
    score = parse_mistral_response(raw_text)
    return score, raw_text


async def save_score(
    client: httpx.AsyncClient,
    token: str,
    case_id: str,
    label: str,
    score: int,
) -> None:
    # same endpoint ResearchEvaluation.jsx uses to save a score
    response = await client.post(
        f"{API_BASE_URL}/evaluation/score",
        json={
            "case_id": case_id,
            "label": label,
            "d5_professional_tone": score,
        },
        headers={"Authorization": f"Bearer {token}"},
        timeout=15.0,
    )
    response.raise_for_status()


async def main():
    logger.info("[mistral_rater] Starting Mistral D5 evaluation run...")
    logger.info(f"[mistral_rater] Model: {MISTRAL_MODEL}")
    logger.info(f"[mistral_rater] Pause between calls: {PAUSE_BETWEEN_CALLS_SECONDS}s")

    mistral_api_key = getattr(settings, "MISTRAL_API_KEY", None)
    if not mistral_api_key:
        logger.error(
            "[mistral_rater] MISTRAL_API_KEY not set in environment. "
            "Add MISTRAL_API_KEY=your_key to your .env file and rebuild."
        )
        sys.exit(1)

    async with httpx.AsyncClient(timeout=30.0) as client:
        token = await get_auth_token(client)
        letters = await fetch_letters(client, token)

        # only score what hasn't been scored yet, so re-runs are cheap
        unscored = [l for l in letters if not l.get("is_scored", False)]
        already_scored = len(letters) - len(unscored)

        logger.info(f"[mistral_rater] {already_scored} already scored, {len(unscored)} remaining.")

        if not unscored:
            logger.info("[mistral_rater] All 180 letters already scored. Nothing to do.")
            return

        success_count = 0
        fail_count = 0
        unparseable_count = 0
        started_at = time.time()

        for i, letter in enumerate(unscored, start=1):
            case_id = letter["case_id"]
            label = letter["label"]
            scenario = letter.get("scenario")
            letter_text = letter.get("referral_letter", "")

            if not letter_text:
                logger.warning(f"[mistral_rater] [{i}/{len(unscored)}] Empty letter text for {case_id} {label} - skipping")
                fail_count += 1
                continue

            try:
                score, raw_text = await score_with_mistral(letter_text)

                if score is None:
                    logger.warning(
                        f"[mistral_rater] [{i}/{len(unscored)}] Unparseable response for "
                        f"{label} scenario={scenario} | raw='{raw_text}' - skipping"
                    )
                    unparseable_count += 1
                    fail_count += 1
                    continue

                await save_score(client, token, case_id, label, score)
                success_count += 1

                logger.info(
                    f"[mistral_rater] [{i}/{len(unscored)}] {label} scenario={scenario} "
                    f"-> score={score} raw='{raw_text}'"
                )

            except Exception as e:
                logger.error(
                    f"[mistral_rater] [{i}/{len(unscored)}] FAILED for {label} {case_id}: {e}",
                    exc_info=True
                )
                fail_count += 1

            # stay under the rate limit
            if i < len(unscored):
                await asyncio.sleep(PAUSE_BETWEEN_CALLS_SECONDS)

        elapsed = round(time.time() - started_at, 1)
        logger.info("=" * 60)
        logger.info(f"[mistral_rater] DONE in {elapsed}s")
        logger.info(f"[mistral_rater] Scored successfully: {success_count}")
        logger.info(f"[mistral_rater] Failed/skipped: {fail_count}")
        logger.info(f"[mistral_rater] Unparseable responses: {unparseable_count}")
        logger.info("=" * 60)

        if fail_count > 0:
            logger.warning(
                f"[mistral_rater] {fail_count} letters were not scored. "
                f"Re-run the script to retry - already-scored letters will be skipped automatically."
            )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except Exception:
        logger.error("[mistral_rater] Script crashed:")
        traceback.print_exc()
        sys.exit(1)