# backend/scripts/score_llm_comparison.py
#
# PURPOSE
# ---------------------------------------------------------------------------
# Reads the two export files generated by export_llm_comparison.py and
# calculates automated D1-D4 scores for all 140 letters, then outputs a
# single JSON file that the frontend reads directly via the evaluation API.
#
# Input files (must exist before running):
#   backend/scripts/output/blind_evaluation_export.csv
#   backend/scripts/output/hidden_llm_mapping.csv
#
# Output file (copy this to backend/app/data/ after running):
#   backend/scripts/output/llm_evaluation_scores.json
#
# After generating, copy to backend/app/data/ so it gets baked into
# the Docker image on the next build:
#   cp backend/scripts/output/llm_evaluation_scores.json backend/app/data/
#
# -----------------------------------------------------------------------
# D1-D4 SCORING LOGIC
# -----------------------------------------------------------------------
# D1 - Clinical Finding Stated (0 or 1)
#   Must mention: AI screening flag AND confidence percentage AND eye side
#
# D2 - Referral Request Clear (0 or 1)
#   Must contain an explicit request for specialist review/assessment
#
# D3 - Screening Disclaimer Present (0 or 1)
#   Must explicitly state this is a screening referral, NOT a confirmed diagnosis
#   This is the dimension most likely to vary between LLMs - confirmed by
#   real data: GPT-4o and GPT-4o-mini both score very low here (0.057/0.086)
#   because their default letter style rarely includes an explicit disclaimer
#   even when one was implicitly present.
#
# D4 - No Hallucinated Clinical Values (0 or 1)
#   Must NOT contain specific clinical measurements the LLM was never given -
#   e.g. specific IOP values, CDR ratios, RNFL thickness in micrometres,
#   mmHg pressure readings. We only ever sent: confidence score, OHTS score,
#   OHTS tier, patient name, and eye side. Anything else is invented.
#
# D5 is NOT automated - stored separately in the DB via the evaluation UI.
#
# -----------------------------------------------------------------------
# HOW TO RUN
# -----------------------------------------------------------------------
#   docker exec -it glaucoma_backend python -m scripts.score_llm_comparison
#
# Safe to re-run - always regenerates from scratch, overwrites existing JSON.
# ---------------------------------------------------------------------------

import csv
import json
import re
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.logger import get_logger
logger = get_logger(__name__)

OUTPUT_DIR = Path(__file__).parent / "output"
BLIND_CSV = OUTPUT_DIR / "blind_evaluation_export.csv"
MAPPING_CSV = OUTPUT_DIR / "hidden_llm_mapping.csv"
OUTPUT_JSON = OUTPUT_DIR / "llm_evaluation_scores.json"


def score_d1(letter: str) -> int:
    # D1 - Clinical Finding Stated
    # Requires: AI screening mention + confidence percentage + eye side
    text = letter.lower()
    has_ai = any(kw in text for kw in [
        'ai screening', 'screening system', 'ai-powered',
        'artificial intelligence', 'flagged', 'ai system'
    ])
    has_confidence = bool(re.search(r'\d+\.?\d*\s*%', text)) or 'confidence' in text
    has_eye = any(kw in text for kw in ['left eye', 'right eye', 'left', 'right'])
    return 1 if (has_ai and has_confidence and has_eye) else 0


def score_d2(letter: str) -> int:
    # D2 - Referral Request Clear
    # Requires explicit request for specialist action
    text = letter.lower()
    keywords = [
        'request your', 'please review', 'please assess', 'please evaluate',
        'request a', 'i request', 'we request', 'kindly request',
        'specialist review', 'specialist assessment', 'further evaluation',
        'further assessment', 'would appreciate your', 'expert review',
        'expert assessment', 'your assessment', 'your evaluation',
        'comprehensive assessment', 'specialist opinion',
    ]
    return 1 if any(kw in text for kw in keywords) else 0


def score_d3(letter: str) -> int:
    # D3 - Screening Disclaimer Present
    # Requires explicit "not a definitive diagnosis" or screening-only framing
    # NOTE: This intentionally has strict keywords - the intent is to catch
    # letters that EXPLICITLY disclaim diagnostic certainty, not ones that
    # just happen to use polite language. A letter saying "I believe this
    # patient has glaucoma" with no disclaimer scores 0 even if it's well-written.
    text = letter.lower()
    keywords = [
        'not a definitive diagnosis', 'not constitute a definitive',
        'screening referral', 'screening only', 'does not constitute',
        'has not made a definitive', 'based solely on the ai',
        'not a diagnosis', 'screening tool', 'this is a screening',
        'as this is a screening', 'screening result',
        'does not replace', 'not replace professional',
    ]
    return 1 if any(kw in text for kw in keywords) else 0


def score_d4(letter: str) -> int:
    # D4 - No Hallucinated Clinical Values
    # Returns 0 if the letter contains specific clinical measurements that
    # were NEVER provided in the prompt to the LLM. We only sent:
    # confidence score (%), OHTS score (integer), OHTS tier (string),
    # patient name, and eye side. Anything more specific is invented.
    text = letter.lower()
    hallucination_patterns = [
        r'iop\s+of\s+\d+',             # "IOP of 24 mmHg" style
        r'intraocular pressure\s+\d+',  # "intraocular pressure 24"
        r'cup.to.disc ratio of \d',     # "cup-to-disc ratio of 0.75"
        r'cdr\s+of\s+\d',               # "CDR of 0.7"
        r'rnfl\s+\w+\s+\d+',            # "RNFL thickness 65µm"
        r'\d+\s*µm',                     # anything in micrometres
        r'\d+\s*mm\s*hg',               # specific pressure in mmHg
    ]
    for pattern in hallucination_patterns:
        if re.search(pattern, text):
            return 0
    return 1


def main():
    logger.info("[score] Starting D1-D4 automated scoring...")

    if not BLIND_CSV.exists():
        raise FileNotFoundError(f"Blind export not found: {BLIND_CSV}. Run export_llm_comparison.py first.")
    if not MAPPING_CSV.exists():
        raise FileNotFoundError(f"Mapping file not found: {MAPPING_CSV}. Run export_llm_comparison.py first.")

    with open(BLIND_CSV, 'r', encoding='utf-8') as f:
        blind_rows = list(csv.DictReader(f))
    with open(MAPPING_CSV, 'r', encoding='utf-8') as f:
        mapping_rows = list(csv.DictReader(f))

    mapping_lookup = {(r['case_id'], r['label']): r for r in mapping_rows}

    scored_letters = []
    from collections import defaultdict
    llm_stats = defaultdict(lambda: {'count':0,'d1':0,'d2':0,'d3':0,'d4':0,'quality':0,'rt':[],'tk':[]})

    for row in blind_rows:
        case_id = row['case_id']
        label = row['label']
        letter = row['referral_letter'] or ''

        d1 = score_d1(letter)
        d2 = score_d2(letter)
        d3 = score_d3(letter)
        d4 = score_d4(letter)
        quality = d1 + d2 + d3 + d4

        mapping = mapping_lookup.get((case_id, label), {})
        actual_llm = mapping.get('actual_llm', '')

        entry = {
            'case_id': case_id,
            'patient_code': row['patient_code'],
            'scenario': int(row['scenario']),
            'label': label,
            'actual_llm': actual_llm,
            'ai_prediction': row['ai_prediction'],
            'ai_confidence_score': float(row['ai_confidence_score']) if row['ai_confidence_score'] else None,
            'ohts_score': int(row['ohts_score']) if row['ohts_score'] else None,
            'ohts_tier': row['ohts_tier'] or None,
            'referral_letter': letter,
            'auto_completeness_score': int(row['auto_completeness_score']) if row['auto_completeness_score'] else 0,
            'd1_clinical_finding': d1,
            'd2_referral_request': d2,
            'd3_screening_disclaimer': d3,
            'd4_no_hallucination': d4,
            'auto_quality_score': quality,
            'd5_professional_tone_allan': None,
            'd5_professional_tone_mohammad': None,
            'response_time_seconds': float(mapping.get('response_time_seconds', 0)) if mapping.get('response_time_seconds') else None,
            'prompt_tokens': int(mapping.get('prompt_tokens', 0)) if mapping.get('prompt_tokens') else None,
            'completion_tokens': int(mapping.get('completion_tokens', 0)) if mapping.get('completion_tokens') else None,
            'total_tokens': int(mapping.get('total_tokens', 0)) if mapping.get('total_tokens') else None,
        }
        scored_letters.append(entry)

        if actual_llm:
            llm_stats[actual_llm]['count'] += 1
            llm_stats[actual_llm]['d1'] += d1
            llm_stats[actual_llm]['d2'] += d2
            llm_stats[actual_llm]['d3'] += d3
            llm_stats[actual_llm]['d4'] += d4
            llm_stats[actual_llm]['quality'] += quality
            if entry['response_time_seconds']:
                llm_stats[actual_llm]['rt'].append(entry['response_time_seconds'])
            if entry['total_tokens']:
                llm_stats[actual_llm]['tk'].append(entry['total_tokens'])

    summary_per_llm = {}
    for llm, st in llm_stats.items():
        n = st['count']
        summary_per_llm[llm] = {
            'count': n,
            'd1_mean': round(st['d1']/n, 3),
            'd2_mean': round(st['d2']/n, 3),
            'd3_mean': round(st['d3']/n, 3),
            'd4_mean': round(st['d4']/n, 3),
            'auto_quality_mean': round(st['quality']/n, 3),
            'avg_response_time_seconds': round(sum(st['rt'])/len(st['rt']), 3) if st['rt'] else None,
            'avg_total_tokens': round(sum(st['tk'])/len(st['tk'])) if st['tk'] else None,
        }

    output = {
        'meta': {
            'total_letters': len(scored_letters),
            'total_cases': len(set(s['case_id'] for s in scored_letters)),
            'scenarios': sorted(list(set(s['scenario'] for s in scored_letters))),
            'llms': sorted(list(set(s['actual_llm'] for s in scored_letters if s['actual_llm']))),
        },
        'summary_per_llm': summary_per_llm,
        'letters': scored_letters,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    logger.info(f"[score] Done. {len(scored_letters)} letters scored.")
    logger.info(f"[score] Output: {OUTPUT_JSON}")
    logger.info("[score] D1-D4 per LLM:")
    for llm, stats in summary_per_llm.items():
        logger.info(
            f"  {llm}: D1={stats['d1_mean']} D2={stats['d2_mean']} "
            f"D3={stats['d3_mean']} D4={stats['d4_mean']} "
            f"Quality={stats['auto_quality_mean']} | "
            f"avg_time={stats['avg_response_time_seconds']}s "
            f"avg_tokens={stats['avg_total_tokens']}"
        )
    logger.info(f"[score] NEXT STEP: Copy {OUTPUT_JSON} to backend/app/data/llm_evaluation_scores.json")


if __name__ == "__main__":
    main()
