"""create initial tables

Revision ID: 100ffe547b56
Revises: 
Create Date: 2026-04-27 17:04:03.280087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100ffe547b56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'non-binary', 'another gender', 'prefer not to say', name='gender_types'), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('landline_number', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('iop', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'nurse', name='user_roles'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('landline_number', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('screenings',
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('screened_by', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('eye_side', sa.Enum('left', 'right', name='eye_side_types'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='screening_status'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screened_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('screening_id')
    )
    op.create_index(op.f('ix_screenings_patient_id'), 'screenings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_screenings_screening_id'), 'screenings', ['screening_id'], unique=False)
    op.create_table('screening_results',
    sa.Column('screening_results_id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('model_used', sa.Enum('efficientnetb0', 'vgg16', 'efficientnetv2', 'ensemble', name='model_types'), nullable=False),
    sa.Column('prediction', sa.Enum('glaucoma', 'normal', name='prediction_types'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('threshold_used', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('gradcam_path', sa.Text(), nullable=True),
    sa.Column('ohts_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ohts_tier', sa.Enum('low', 'possible', 'critical', name='ohts_tier_types'), nullable=True),
    sa.Column('referral_letter', sa.Text(), nullable=True),
    sa.Column('llm_used', sa.Enum('gpt4o', 'gpt4o_mini', 'llama', 'gemini', name='llm_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.screening_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('screening_results_id')
    )
    op.create_index(op.f('ix_screening_results_screening_id'), 'screening_results', ['screening_id'], unique=False)
    op.create_index(op.f('ix_screening_results_screening_results_id'), 'screening_results', ['screening_results_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_results_screening_results_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_screening_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_screenings_screening_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_patient_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
