"""add disagreement fields and letter_type to screening_results

Revision ID: 25fee8d12ff7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-28 22:46:00.433532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25fee8d12ff7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_evaluation_scores')
    op.add_column('screening_results', sa.Column('has_model_disagreement', sa.Boolean(), nullable=True))
    op.add_column('screening_results', sa.Column('disagreement_model', sa.String(length=50), nullable=True))
    op.add_column('screening_results', sa.Column('disagreement_confidence', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('screening_results', sa.Column('letter_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'letter_type')
    op.drop_column('screening_results', 'disagreement_confidence')
    op.drop_column('screening_results', 'disagreement_model')
    op.drop_column('screening_results', 'has_model_disagreement')
    op.create_table('llm_evaluation_scores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scorer_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('d5_professional_tone', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scorer_user_id'], ['users.user_id'], name=op.f('llm_evaluation_scores_scorer_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_evaluation_scores_pkey')),
    sa.UniqueConstraint('case_id', 'label', 'scorer_user_id', name=op.f('uq_evaluation_score'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
