"""add user_tokens table

Revision ID: 27197be5bd29
Revises: 100ffe547b56
Create Date: 2026-04-27 20:16:27.386608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27197be5bd29'
down_revision: Union[str, Sequence[str], None] = '100ffe547b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.Enum('activation', 'password_reset', name='token_type_enum'), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_user_tokens_token'), 'user_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_user_tokens_token_id'), 'user_tokens', ['token_id'], unique=False)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token'), table_name='user_tokens')
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
