"""add generation_time_ms to screening_results

Revision ID: 3ab6af702738
Revises: 791692f6b39a
Create Date: 2026-05-23 14:01:16.702205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab6af702738'
down_revision: Union[str, Sequence[str], None] = '791692f6b39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_results', sa.Column('generation_time_ms', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'generation_time_ms')
    # ### end Alembic commands ###
