"""add failed_login_attempts_ and is_locked to users

Revision ID: 5a6c3493af5b
Revises: db6875339de1
Create Date: 2026-06-17 12:56:08.241694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6c3493af5b'
down_revision: Union[str, Sequence[str], None] = 'db6875339de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
