"""add report history table

Revision ID: 60faecaf30f0
Revises: 8f1406e34ff3
Create Date: 2026-06-02 17:01:06.127872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60faecaf30f0'
down_revision: Union[str, Sequence[str], None] = '8f1406e34ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('report_history_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_title', sa.String(length=255), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_name', sa.String(length=255), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('report_history_id')
    )
    op.create_index(op.f('ix_report_history_created_at'), 'report_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_history_generated_by_user_id'), 'report_history', ['generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_report_history_report_history_id'), 'report_history', ['report_history_id'], unique=False)
    op.create_index(op.f('ix_report_history_report_type'), 'report_history', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_history_status'), 'report_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_history_status'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_report_type'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_report_history_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_generated_by_user_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_created_at'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
