"""add cdr disc_radius cup_raduis to screening results

Revision ID: cf1e3f89386e
Revises: 3ab6af702738
Create Date: 2026-05-25 11:40:39.999147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1e3f89386e'
down_revision: Union[str, Sequence[str], None] = '3ab6af702738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_results', sa.Column('cdr', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('screening_results', sa.Column('disc_radius', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('screening_results', sa.Column('cup_radius', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'cup_radius')
    op.drop_column('screening_results', 'disc_radius')
    op.drop_column('screening_results', 'cdr')
    # ### end Alembic commands ###
